accountapp/urls.py
from django.contrib import admin
from django.urls import path
from .views import (home_view, 
login_view, 
logout_view,
login_form_view,
profile_view,
permission_view,


UserList,
users_template_view,
user_template_view,
user_create,
user_edit,
user_delete,
users_group_template_view,
user_make_manager,


CredentialList,
credentials_template_view,
credential_delete,
credential_create,
credential_edit,
credential_add_to_user_template,
credential_add_to_user,
credential_add_to_group_template,
credential_add_to_group,


GroupList,
groups_template_view,
group_create,
group_edit,
group_delete,
group_add_to_user_template,
group_add_to_user,
groups_user_template,
)

app_name = "accountapp"

urlpatterns = [

    ####groups--------------
    #api view-----
    path('api/groups/', GroupList.as_view()),
    #view
    path('group/', groups_template_view, name='groups_template_view'),
    path('group/create/', group_create, name='group_create'),
    path('group/edit/<int:id>/', group_edit, name='group_edit'),
    path('group/delete/<int:id>/', group_delete, name='group_delete'),
    path('group/add_user/template/<int:id>/', group_add_to_user_template, name='group_add_to_user_template'),
    path('group/add_user/<int:group_id>/<int:user_id>/', group_add_to_user, name='group_add_to_user'),
    path('group/user/<int:group_id>/', groups_user_template, name='groups_user_template'),


    ####credentials--------------
    #api view-----
    path('api/credentials/', CredentialList.as_view()),
    #view
    path('credential/', credentials_template_view, name='credentials_template_view'),
    path('credential/create/', credential_create, name='credential_create'),
    path('credential/edit/<int:id>/', credential_edit, name='credential_edit'),
    path('credential/delete/<int:id>/', credential_delete, name='credential_delete'),
    path('credential/add_user/template/<int:id>/', credential_add_to_user_template, name='credential_add_to_user_template'),
    path('credential/add_user/<int:credential_id>/<int:user_id>/', credential_add_to_user, name='credential_add_to_user'),
    path('credential/add_group/template/<int:id>/', credential_add_to_group_template, name='credential_add_to_group_template'),
    path('credential/add_group/<int:credential_id>/<int:group_id>/', credential_add_to_group, name='credential_add_to_group'),


    
    ###user---------------------
    #api view-----
    path('api/users/', UserList.as_view()),
    #view
    path('user/', users_template_view, name='users_template_view'),
    path('user/<int:id>/', user_template_view, name='user_template_view'),
    path('user/create/', user_create, name='user_create'),
    path('user/edit/<int:id>/', user_edit, name='user_edit'),
    path('user/delete/<int:id>/', user_delete, name='user_delete'),
    path('user/group/<int:id>/', users_group_template_view, name='users_group_template_view'),
    path('user/make_manager/<int:id>/', user_make_manager, name='user_make_manager'),


    ###home-------------------------
    #api view-----
    #view
    path('', home_view, name='home_view'),


    ###auth-------------------------
    #api view-----
    #view

    #login
    path('login/', login_form_view, name='login_form_view'),
    path('login_view/', login_view, name='login_view'),

    #logout
    path('logout/', logout_view, name='logout_view'),

    #profile
    path('profile/', profile_view, name='profile_view'),

    #persmission
    path('permission', permission_view, name='permission'),


]

passprofile/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accountapp.urls')),
]

accountapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class UserType(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class User(AbstractUser):
    user_type = models.ForeignKey(UserType, on_delete=models.CASCADE)
    raw_password = models.CharField(max_length=30, null=True, blank=True)
    # creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_groups", blank=True,null=True)

    


class UserGroup(models.Model):
    name = models.CharField(max_length=300, null=True, blank=False)
    user = models.ManyToManyField(User, blank=True)
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_groups", blank=True,null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

accountapp/forms.py
from django import forms 
from masterapp.models import Credential, User, UserGroup

class CredentialForm(forms.ModelForm): 

    product = forms.CharField( max_length=30, min_length=3)
    username = forms.CharField( max_length=30, min_length=3)
    password = forms.CharField( max_length=30, min_length=3)

	# specify the name of model to use 
    class Meta:
        model = Credential
        fields = ['product', 'username', 'password']


class UserForm(forms.ModelForm): 
    username = forms.CharField(max_length=30, min_length=3)
    first_name = forms.CharField( max_length=30, min_length=3)
    last_name = forms.CharField( max_length=30, min_length=3)
    # password = forms.CharField( max_length=30, min_length=3)

	# specify the name of model to use 
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'password']

class UserEditForm(forms.ModelForm): 
    username = forms.CharField(max_length=30, min_length=3)
    first_name = forms.CharField( max_length=30, min_length=3)
    last_name = forms.CharField( max_length=30, min_length=3)
    raw_password = forms.CharField( max_length=30, min_length=3)

	# specify the name of model to use 
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'raw_password']


class GroupForm(forms.ModelForm):
     
    name = forms.CharField( max_length=30, min_length=3)
    
	# specify the name of model to use 
    class Meta:
        model = UserGroup
        fields = ['name']

accountapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from masterapp.models import Credential
from accountapp.models import UserGroup, User, UserType
from .forms import CredentialForm, UserForm, GroupForm, UserEditForm
from django.db.models import Q
from .serializers import CredentialSerializer, UserSerializer, GroupSerializer
from django.http import Http404
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework.permissions import IsAuthenticated

admin_and_manager = ["admin", "manager"]


#TODO GROUP======================

class GroupList(APIView):
    """
    List all groups
    """

    # if current user belongs to this credentials
    def get(self, request, format=None):

        try:
            credential_id = request.GET.get("credential_id")
        except:
            credential_id = ""

        try:
            user_id = request.GET.get("user_id")
        except:
            user_id = ""

        try:
            manager_id = request.GET.get("manager_id")
        except:
            manager_id = ""

        

        all_groups_object = None
        
        if user_id:
            user_obj = User.objects.get(id = user_id)
            all_groups_object = user_obj.usergroup_set.all()
        else:
            all_groups_object = UserGroup.objects.all()

        try:
            start = int(request.GET.get("start"))
        except:
            start = 0
        try:
            length = int(request.GET.get("length"))
        except: 
            length = 10
        try:
            draw = request.GET.get("draw")
        except:
            draw = 1

        search_query = request.GET.get("search[value]")
        order = request.GET.get("order[0][dir]")
        orderable_column = request.GET.get("order[0][column]")
        recordsTotal = len(all_groups_object)
        orderable_column_name = ""

        if orderable_column == "0":
            orderable_column_name = "name"
        elif orderable_column == "1":
            orderable_column_name = "creator"
        

        if search_query  and orderable_column != "":
            if order == "asc":
                all_groups_object = all_groups_object.filter(
                    Q(name__icontains=search_query) |
                    Q(creator__username__icontains=search_query) 
                ).order_by(orderable_column_name)
            else:
                all_groups_object = all_groups_object.filter(
                    Q(name__icontains=search_query) |
                    Q(creator__username__icontains=search_query) 
                ).order_by("-"+orderable_column_name)
        elif search_query:
            all_groups_object = all_groups_object.filter(
                    Q(name__icontains=search_query) |
                    Q(creator__username__icontains=search_query) 
            )
        elif orderable_column:
            if order == "asc":
                all_groups_object = all_groups_object.order_by(orderable_column_name)
            else:
                all_groups_object = all_groups_object.order_by("-"+orderable_column_name)

        recordsFiltered = len(all_groups_object)
        items = all_groups_object[start:start+length]
        serializer = GroupSerializer(items, many=True)
        result = {}
        result["data"] = serializer.data

        #TODO to check if group is present in this credentials
        if credential_id:
            for data in result["data"]:
                group_object = UserGroup.objects.get(id = data["id"])
                credential_object = Credential.objects.get(id = credential_id)
                group_in_credentials_objects = credential_object.user_group.all()

                if group_object in group_in_credentials_objects:
                    data.update({'group_present':["true", data["id"]]})
                else:
                    data.update({'group_present':["false", data["id"]]})

        result["draw"] = draw
        result["recordsFiltered"] = recordsFiltered
        result["recordsTotal"] = recordsTotal
        return Response(result)


@login_required
def groups_template_view(request):
    group_objects = UserGroup.objects.all()[::-1]
    context = {
        "group_objects":group_objects,
    }
    return render(request, "accountapp/groups.html", context)

@login_required
def group_create(request):
    if request.method == 'POST':
        form = GroupForm(request.POST)
        if form.is_valid():
            messages.success(request, 'The form is valid.')
            instance = form.save()
            instance.creator = request.user
            instance.save()
        else:
            messages.error(request, form.errors )
            return redirect("accountapp:group_create")

        return redirect("accountapp:groups_template_view")
    else:
        form = GroupForm()
    return render(request, 'accountapp/group_create.html', {'form': form}) 

@login_required
def group_edit(request, id=None):
    group = get_object_or_404(UserGroup, id=id)
    if request.method == "POST":
        form = GroupForm(request.POST, instance=group)
        if form.is_valid():
            form.save()
        else:
            return redirect('/group/edit/'+str(id)+'/')
        return redirect('accountapp:groups_template_view')
    else:
        form = GroupForm(instance=group)
    return render(request, 'accountapp/group_edit.html', {'form': form,'group': group})

@login_required
def group_delete(request, id):
    group = UserGroup.objects.get(id = id)
    group.delete()
    return redirect("accountapp:groups_template_view")

@login_required
def group_add_to_user_template(request, id=None):
    group_object = UserGroup.objects.get(id = id)
    context={
        "group_object":group_object
    }
    return render(request, 'accountapp/group_add_to_user_template.html', context)

@login_required
def group_add_to_user(request, group_id, user_id):
    '''
    To add and remove user from group
    '''
    user_object = User.objects.get(id = user_id)
    group_object = UserGroup.objects.get(id = group_id)
    users_in_group_object = group_object.user.all()

    if user_object in users_in_group_object:
        #remove user from group
        group_object.user.remove(user_object) 
    else:
        #add user in group
        group_object.user.add(user_object) 

    return redirect('/group/add_user/template/'+str(group_id)+'/')

@login_required
def groups_user_template(request, group_id):
    group_object = UserGroup.objects.get(id = group_id)
    context={ 
        "group_object":group_object
        }
    return render(request, 'accountapp/groups_user_template.html', context)



# TODO USER====================================

class UserList(APIView):
    """
    List all users, or create a new users.
    """
    permission_classes = (IsAuthenticated,)

    def get(self, request, format=None):

        if request.user.user_type.name in admin_and_manager:

            # if current user belongs to this credentials
            try:
                credential_id = request.GET.get("credential_id")
            except:
                credential_id = ""

            try:
                group_id = request.GET.get("group_id")
            except:
                group_id = ""

            try:
                group_id_to_show_user = request.GET.get("group_id_to_show_user")
            except:
                group_id_to_show_user = ""

            all_users_object = None

            if group_id_to_show_user:
                group_object = UserGroup.objects.get(id = group_id_to_show_user)
                all_users_object = group_object.user.all()
            else:
                all_users_object = User.objects.all()

            try:
                start = int(request.GET.get("start"))
            except:
                start = 0
            try:
                length = int(request.GET.get("length"))
            except: 
                length = 10
            try:
                draw = request.GET.get("draw")
            except:
                draw = 1

            search_query = request.GET.get("search[value]")
            order = request.GET.get("order[0][dir]")
            orderable_column = request.GET.get("order[0][column]")
            recordsTotal = len(all_users_object)
            orderable_column_name = ""

            if orderable_column == "0":
                orderable_column_name = "username"
            elif orderable_column == "1":
                orderable_column_name = "first_name"
            elif orderable_column == "2":
                orderable_column_name = "last_name"
            elif orderable_column == "3":
                orderable_column_name = "user_type"

            if search_query  and orderable_column != "":
                if order == "asc":
                    all_users_object = all_users_object.filter(
                        Q(username__icontains=search_query) |
                        Q(first_name__icontains=search_query) |
                        Q(last_name__icontains=search_query)|
                        Q(user_type__name__icontains=search_query)
                    ).order_by(orderable_column_name)
                else:
                    all_users_object = all_users_object.filter(
                        Q(username__icontains=search_query) |
                        Q(first_name__icontains=search_query) |
                        Q(last_name__icontains=search_query)|
                        Q(user_type__name__icontains=search_query)
                    ).order_by("-"+orderable_column_name)
            elif search_query:
                all_users_object = all_users_object.filter(
                        Q(username__icontains=search_query) |
                        Q(first_name__icontains=search_query) |

accountapp/templates/snippets/sidebar.html
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    {% if request.user.user_type.name != "user"  %}
    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Pass Profile</div>
    </a>
    {% else %}
    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/profile">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Pass Profile</div>
    </a>
    {% endif %}

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    {% if request.user.user_type.name != "user"%}



    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href="/">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Tables
    </div>

    <!-- Nav Item - Tables -->
    <li class="nav-item">
        <a class="nav-link" href="{% url 'accountapp:groups_template_view' %}">
            <i class="fas fa-fw fa-table"></i>
            <span>Groups</span></a>
    </li>

    <!-- Nav Item - Tables -->
    <li class="nav-item">
        <a class="nav-link" href="{% url 'accountapp:users_template_view' %}">
            <i class="fas fa-fw fa-table"></i>
            <span>Users</span></a>
    </li>

    <!-- Nav Item - Tables -->
    <li class="nav-item">
        <a class="nav-link" href="{% url 'accountapp:credentials_template_view' %}">
            <i class="fas fa-fw fa-table"></i>
            <span>Credentials</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Create
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true"
            aria-controls="collapseTwo">
            <i class="fas fa-plus-square"></i>
            <span>Create</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" href="{% url 'accountapp:group_create' %}">Group</a>
                <a class="collapse-item" href="{% url 'accountapp:user_create' %}">User</a>
                <a class="collapse-item" href="{% url 'accountapp:credential_create' %}">Credential</a>
            </div>
        </div>
    </li>

    
    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>
    {% else %}


    <li class="nav-item active">
        <a class="nav-link" href="#">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Welcome, {{request.user.first_name}}</span></a>
    </li>

    <hr class="sidebar-divider d-none d-md-block">
      <!-- Nav Item - Tables -->
      <li class="nav-item">
        <a class="nav-link" href="/profile">
            <i class="fas fa-fw fa-table"></i>
            <span>Profile</span></a>
    </li>


    {% endif %}


</ul>

accountapp/templates/snippets/topbar.html
{% load static %}
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Search -->


    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">
        
        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{request.user.get_full_name}}</span>
                <img class="img-profile rounded-circle" src="{% static 'img/undraw_profile.svg' %}">

            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{% url 'accountapp:profile_view' %}">
                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                    Profile
                </a>
                <!-- <a class="dropdown-item" href="#">
                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                    Settings
                </a>
                <a class="dropdown-item" href="#">
                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                    Activity Log
                </a> -->
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'accountapp:logout_view' %}" data-toggle="modal" data-target="#logoutModal">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Logout
                </a>
            </div>
        </li>

    </ul>

</nav>